============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: C:\Users\Chris\exercism\python\meetup, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 97 items

meetup_test.py .....................................................F... [ 58%]
........................................                                 [100%]

================================== FAILURES ===================================
__________ MeetupTest.test_nonexistent_fifth_monday_of_february_2015 __________

self = <meetup_test.MeetupTest testMethod=test_nonexistent_fifth_monday_of_february_2015>

    def test_nonexistent_fifth_monday_of_february_2015(self):
        self.assertRaises(MeetupDayException, meetup_day, 2015, 2, 'Monday',
>                         '5th')

meetup_test.py:403: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def meetup_day(year, month, weekday, which):
    
        day = datetime.date(year, month, 1)
    
        while day.month == month:
            if day.weekday() == WEEKDAY[weekday] and WHICH[which](day):
                return day
            day += datetime.timedelta(days=1)
    
>       raise Exception("Not a valid meetup day")
E       Exception: Not a valid meetup day

meetup.py:26: Exception
===================== 1 failed, 96 passed in 0.44 seconds =====================
